### ISSUE TITLE
can't download book

### ISSUE THREAD

**Issue by PiSaucer** [JRyanHall16/textLayer#1]
I tried to use this program and I get this error:

```python
Traceback (most recent call last):
  File "textlayer.py", line 146, in <module>
    tileTitle = driver.find_element_by_xpath(tileTitlePath).get_attribute('textContent')
  File "C:\Users\pisau\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\pisau\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\pisau\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\pisau\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div/span/ui-view/div/div/nav/span[3]
```

**Comment by JRyanHall16** [comment]
I'll need to know what title you are trying to download. If you could provide that information here, I will try to work out your issue :)
